// Phase B5.3 — Material icon theme bundle tests.
//
// Exercises `loadMaterialIconTheme()` against the inlined bundle
// generated by `scripts/build-material.mjs`. Asserts that common
// filetypes resolve to distinct upstream icon ids and that each
// resolution carries a renderable payload (`iconPath` or `inlineSvg`).
//
// If the bundle is the offline-fallback stub, the content assertions
// skip cleanly — we still confirm the dynamic import doesn't throw
// and the theme object is well-formed.

import { test, before, after } from 'node:test';
import { strict as assert } from 'node:assert';
import { Window } from 'happy-dom';

let win;

before(() => {
  win = new Window();
  globalThis.DOMParser = win.DOMParser;
  globalThis.XMLSerializer = win.XMLSerializer;
  globalThis.Element = win.Element;
});

after(async () => {
  delete globalThis.DOMParser;
  delete globalThis.XMLSerializer;
  delete globalThis.Element;
  await win.happyDOM.close();
});

const KIND_FILE = 0;
const KIND_DIR = 1;

function fileEntry(name, languageId) {
  const e = { name, kind: KIND_FILE };
  if (languageId !== undefined) e.languageId = languageId;
  return e;
}
function dirEntry(name) {
  return { name, kind: KIND_DIR };
}

const { loadMaterialIconTheme } = await import('../dist/icons-material.js');
const { createIconResolver } = await import('../dist/icons/resolver.js');

// Detect whether the generated bundle is the offline stub so we can
// degrade content-assertions cleanly. The stub's theme has exactly
// two icon ids (`_stub_file`, `_stub_folder`); the real bundle has
// 150+.
const generated = await import('../dist/icons/material/generated.js');
const IS_STUB =
  generated.MATERIAL_THEME_IS_STUB === true ||
  Object.keys(generated.materialIconTheme.iconDefinitions).length < 10;

test('loadMaterialIconTheme: dynamic import resolves without throwing', async () => {
  const theme = await loadMaterialIconTheme();
  assert.equal(theme.id, 'material');
  assert.ok(theme.iconDefinitions, 'iconDefinitions must be present');
  assert.ok(theme.file, 'theme.file must be set');
  assert.ok(theme.folder, 'theme.folder must be set');
});

test('Material: default file + folder icons carry renderable payloads', async () => {
  const theme = await loadMaterialIconTheme();
  const fileDef = theme.iconDefinitions[theme.file];
  const folderDef = theme.iconDefinitions[theme.folder];
  assert.ok(fileDef, 'file definition exists');
  assert.ok(folderDef, 'folder definition exists');
  assert.ok(
    fileDef.inlineSvg !== undefined || fileDef.iconPath !== undefined,
    'file def has inlineSvg or iconPath',
  );
  assert.ok(
    folderDef.inlineSvg !== undefined || folderDef.iconPath !== undefined,
    'folder def has inlineSvg or iconPath',
  );
});

// ─── Content assertions — run only against the real bundle ──────────

test('Material: resolver returns distinct icon ids for common files', async (t) => {
  if (IS_STUB) {
    t.skip('offline stub — skipping content assertion');
    return;
  }
  const theme = await loadMaterialIconTheme();
  const resolver = createIconResolver(theme, 'dark');

  const cases = [
    fileEntry('foo.ts'),
    fileEntry('foo.js'),
    fileEntry('package.json'),
    fileEntry('README.md'),
    fileEntry('foo.py'),
    fileEntry('foo.rs'),
    fileEntry('Dockerfile'),
    fileEntry('tsconfig.json'),
  ];

  const resolved = cases.map((e) => {
    const r = resolver(e);
    assert.ok(r !== null, `resolver returned null for ${e.name}`);
    return r;
  });

  const ids = resolved.map((r) => r.iconId);
  const unique = new Set(ids);
  assert.equal(
    unique.size,
    ids.length,
    `expected distinct iconIds, got collisions in ${JSON.stringify(ids)}`,
  );
});

test('Material: each resolved icon has iconPath or inlineSvg populated', async (t) => {
  if (IS_STUB) {
    t.skip('offline stub — skipping content assertion');
    return;
  }
  const theme = await loadMaterialIconTheme();
  const resolver = createIconResolver(theme, 'dark');

  const samples = [
    fileEntry('foo.ts'),
    fileEntry('foo.js'),
    fileEntry('package.json'),
    fileEntry('README.md'),
    fileEntry('foo.py'),
    fileEntry('foo.rs'),
    fileEntry('Dockerfile'),
    fileEntry('tsconfig.json'),
    dirEntry('src'),
  ];
  for (const s of samples) {
    const r = resolver(s);
    assert.ok(r !== null, `resolver returned null for ${s.name}`);
    const def = r.definition;
    assert.ok(
      def.inlineSvg !== undefined || def.iconPath !== undefined,
      `${s.name} → ${r.iconId} missing iconPath and inlineSvg`,
    );
  }
});
