// The built-in default icon theme. Ships with every installation of
// mille-ui; used as the fallback when no custom theme is supplied.
//
// Coverage is intentionally narrow (~20 common file types) to keep
// the gzipped size under the 4 KB budget. Consumers who want fuller
// coverage bring their own VS Code-format theme via `loadIconTheme`.

import {
  FILE_CSS_SVG,
  FILE_ENV_SVG,
  FILE_GIT_SVG,
  FILE_GO_SVG,
  FILE_HTML_SVG,
  FILE_IMAGE_SVG,
  FILE_JS_SVG,
  FILE_JSON_SVG,
  FILE_LOCK_SVG,
  FILE_MD_SVG,
  FILE_PY_SVG,
  FILE_README_SVG,
  FILE_RS_SVG,
  FILE_SVG,
  FILE_TOML_SVG,
  FILE_TS_SVG,
  FILE_YAML_SVG,
  FOLDER_OPEN_SVG,
  FOLDER_SVG,
} from './assets/index.js';
import type { IconTheme } from './types.js';

export const defaultIconTheme: IconTheme = {
  id: 'mille-default',
  iconDefinitions: {
    _file: { inlineSvg: FILE_SVG },
    _folder: { inlineSvg: FOLDER_SVG },
    _folder_open: { inlineSvg: FOLDER_OPEN_SVG },
    _ts: { inlineSvg: FILE_TS_SVG },
    _js: { inlineSvg: FILE_JS_SVG },
    _json: { inlineSvg: FILE_JSON_SVG },
    _md: { inlineSvg: FILE_MD_SVG },
    _py: { inlineSvg: FILE_PY_SVG },
    _rs: { inlineSvg: FILE_RS_SVG },
    _go: { inlineSvg: FILE_GO_SVG },
    _css: { inlineSvg: FILE_CSS_SVG },
    _html: { inlineSvg: FILE_HTML_SVG },
    _yaml: { inlineSvg: FILE_YAML_SVG },
    _toml: { inlineSvg: FILE_TOML_SVG },
    _lock: { inlineSvg: FILE_LOCK_SVG },
    _git: { inlineSvg: FILE_GIT_SVG },
    _env: { inlineSvg: FILE_ENV_SVG },
    _image: { inlineSvg: FILE_IMAGE_SVG },
    _readme: { inlineSvg: FILE_README_SVG },
  },
  file: '_file',
  folder: '_folder',
  folderExpanded: '_folder_open',
  fileExtensions: {
    ts: '_ts',
    tsx: '_ts',
    mts: '_ts',
    cts: '_ts',
    js: '_js',
    jsx: '_js',
    mjs: '_js',
    cjs: '_js',
    json: '_json',
    jsonc: '_json',
    json5: '_json',
    md: '_md',
    markdown: '_md',
    mdx: '_md',
    py: '_py',
    pyi: '_py',
    rs: '_rs',
    go: '_go',
    css: '_css',
    scss: '_css',
    sass: '_css',
    less: '_css',
    html: '_html',
    htm: '_html',
    xhtml: '_html',
    yaml: '_yaml',
    yml: '_yaml',
    toml: '_toml',
    lock: '_lock',
    png: '_image',
    jpg: '_image',
    jpeg: '_image',
    gif: '_image',
    webp: '_image',
    svg: '_image',
    ico: '_image',
    avif: '_image',
    bmp: '_image',
    // Dotfile extensions — the resolver yields the post-dot name
    // verbatim for `.env`, `.gitignore`, etc.
    env: '_env',
    gitignore: '_git',
    gitattributes: '_git',
    gitmodules: '_git',
  },
  fileNames: {
    'readme.md': '_readme',
    'readme.txt': '_readme',
    readme: '_readme',
    'readme.markdown': '_readme',
    'package-lock.json': '_lock',
    'yarn.lock': '_lock',
    'pnpm-lock.yaml': '_lock',
    'cargo.lock': '_lock',
    'bun.lockb': '_lock',
    '.env': '_env',
    '.env.local': '_env',
    '.env.development': '_env',
    '.env.production': '_env',
    '.gitignore': '_git',
    '.gitattributes': '_git',
    '.gitmodules': '_git',
  },
};
