// Soft-duotone icon theme — filled blue folders + dark file body with
// a language-color chip. Chosen as the scannable middle ground between
// default monoline and full Material (docs/icons-preview.html).

import {
  DUOTONE_CSS,
  DUOTONE_ENV,
  DUOTONE_FILE,
  DUOTONE_FOLDER,
  DUOTONE_FOLDER_OPEN,
  DUOTONE_GIT,
  DUOTONE_GO,
  DUOTONE_HTML,
  DUOTONE_IMAGE,
  DUOTONE_JS,
  DUOTONE_JSON,
  DUOTONE_LOCK,
  DUOTONE_MD,
  DUOTONE_PY,
  DUOTONE_README,
  DUOTONE_RS,
  DUOTONE_TOML,
  DUOTONE_TS,
  DUOTONE_YAML,
} from './duotone-assets.js';
import type { IconTheme } from './types.js';

export const duotoneIconTheme: IconTheme = {
  id: 'mille-duotone',
  iconDefinitions: {
    _file: { inlineSvg: DUOTONE_FILE },
    _folder: { inlineSvg: DUOTONE_FOLDER },
    _folder_open: { inlineSvg: DUOTONE_FOLDER_OPEN },
    _ts: { inlineSvg: DUOTONE_TS },
    _js: { inlineSvg: DUOTONE_JS },
    _json: { inlineSvg: DUOTONE_JSON },
    _md: { inlineSvg: DUOTONE_MD },
    _py: { inlineSvg: DUOTONE_PY },
    _rs: { inlineSvg: DUOTONE_RS },
    _go: { inlineSvg: DUOTONE_GO },
    _css: { inlineSvg: DUOTONE_CSS },
    _html: { inlineSvg: DUOTONE_HTML },
    _yaml: { inlineSvg: DUOTONE_YAML },
    _toml: { inlineSvg: DUOTONE_TOML },
    _lock: { inlineSvg: DUOTONE_LOCK },
    _git: { inlineSvg: DUOTONE_GIT },
    _env: { inlineSvg: DUOTONE_ENV },
    _image: { inlineSvg: DUOTONE_IMAGE },
    _readme: { inlineSvg: DUOTONE_README },
  },
  file: '_file',
  folder: '_folder',
  folderExpanded: '_folder_open',
  fileExtensions: {
    ts: '_ts',
    tsx: '_ts',
    mts: '_ts',
    cts: '_ts',
    js: '_js',
    jsx: '_js',
    mjs: '_js',
    cjs: '_js',
    json: '_json',
    jsonc: '_json',
    json5: '_json',
    md: '_md',
    markdown: '_md',
    mdx: '_md',
    py: '_py',
    pyi: '_py',
    rs: '_rs',
    go: '_go',
    css: '_css',
    scss: '_css',
    sass: '_css',
    less: '_css',
    html: '_html',
    htm: '_html',
    xhtml: '_html',
    yaml: '_yaml',
    yml: '_yaml',
    toml: '_toml',
    lock: '_lock',
    png: '_image',
    jpg: '_image',
    jpeg: '_image',
    gif: '_image',
    webp: '_image',
    svg: '_image',
    ico: '_image',
    avif: '_image',
    bmp: '_image',
    env: '_env',
    gitignore: '_git',
    gitattributes: '_git',
    gitmodules: '_git',
  },
  fileNames: {
    'readme.md': '_readme',
    'readme.txt': '_readme',
    readme: '_readme',
    'readme.markdown': '_readme',
    'package-lock.json': '_lock',
    'yarn.lock': '_lock',
    'pnpm-lock.yaml': '_lock',
    'cargo.lock': '_lock',
    'bun.lockb': '_lock',
    '.env': '_env',
    '.env.local': '_env',
    '.env.development': '_env',
    '.env.production': '_env',
    '.gitignore': '_git',
    '.gitattributes': '_git',
    '.gitmodules': '_git',
  },
};
